// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages
type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type URLReturnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLReturnerRequest) Reset() {
	*x = URLReturnerRequest{}
	mi := &file_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLReturnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLReturnerRequest) ProtoMessage() {}

func (x *URLReturnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLReturnerRequest.ProtoReflect.Descriptor instead.
func (*URLReturnerRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *URLReturnerRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type URLReturnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLReturnerResponse) Reset() {
	*x = URLReturnerResponse{}
	mi := &file_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLReturnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLReturnerResponse) ProtoMessage() {}

func (x *URLReturnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLReturnerResponse.ProtoReflect.Descriptor instead.
func (*URLReturnerResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *URLReturnerResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*ShortenBatchRequest `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchListRequest) Reset() {
	*x = ShortenBatchListRequest{}
	mi := &file_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchListRequest) ProtoMessage() {}

func (x *ShortenBatchListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchListRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchListRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenBatchListRequest) GetUrls() []*ShortenBatchRequest {
	if x != nil {
		return x.Urls
	}
	return nil
}

type ShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenBatchRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Urls          []*ShortenBatchResponse `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchListResponse) Reset() {
	*x = ShortenBatchListResponse{}
	mi := &file_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchListResponse) ProtoMessage() {}

func (x *ShortenBatchListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchListResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchListResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *ShortenBatchListResponse) GetUrls() []*ShortenBatchResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *ShortenBatchResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlsRequest) Reset() {
	*x = UrlsRequest{}
	mi := &file_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlsRequest) ProtoMessage() {}

func (x *UrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlsRequest.ProtoReflect.Descriptor instead.
func (*UrlsRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *UrlsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlsResponse) Reset() {
	*x = UrlsResponse{}
	mi := &file_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlsResponse) ProtoMessage() {}

func (x *UrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlsResponse.ProtoReflect.Descriptor instead.
func (*UrlsResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *UrlsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type DeleteUrlsAsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShortUrls     []string               `protobuf:"bytes,2,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUrlsAsyncRequest) Reset() {
	*x = DeleteUrlsAsyncRequest{}
	mi := &file_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUrlsAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlsAsyncRequest) ProtoMessage() {}

func (x *DeleteUrlsAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlsAsyncRequest.ProtoReflect.Descriptor instead.
func (*DeleteUrlsAsyncRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUrlsAsyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUrlsAsyncRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

type DeleteUrlsAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUrlsAsyncResponse) Reset() {
	*x = DeleteUrlsAsyncResponse{}
	mi := &file_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUrlsAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUrlsAsyncResponse) ProtoMessage() {}

func (x *DeleteUrlsAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUrlsAsyncResponse.ProtoReflect.Descriptor instead.
func (*DeleteUrlsAsyncResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUrlsAsyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{13}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlsCount     int32                  `protobuf:"varint,1,opt,name=urls_count,json=urlsCount,proto3" json:"urls_count,omitempty"`
	UsersCount    int32                  `protobuf:"varint,2,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *StatsResponse) GetUrlsCount() int32 {
	if x != nil {
		return x.UrlsCount
	}
	return 0
}

func (x *StatsResponse) GetUsersCount() int32 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

var File_shortener_proto protoreflect.FileDescriptor

const file_shortener_proto_rawDesc = "" +
	"\n" +
	"\x0fshortener.proto\x12\furlshortener\"\"\n" +
	"\x0eShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\x0fShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"1\n" +
	"\x12URLReturnerRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"8\n" +
	"\x13URLReturnerResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"P\n" +
	"\x17ShortenBatchListRequest\x125\n" +
	"\x04urls\x18\x01 \x03(\v2!.urlshortener.ShortenBatchRequestR\x04urls\"_\n" +
	"\x13ShortenBatchRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"R\n" +
	"\x18ShortenBatchListResponse\x126\n" +
	"\x04urls\x18\x01 \x03(\v2\".urlshortener.ShortenBatchResponseR\x04urls\"Z\n" +
	"\x14ShortenBatchResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"&\n" +
	"\vUrlsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\fUrlsResponse\x12)\n" +
	"\x04urls\x18\x01 \x03(\v2\x15.urlshortener.UserURLR\x04urls\"I\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"P\n" +
	"\x16DeleteUrlsAsyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x02 \x03(\tR\tshortUrls\"3\n" +
	"\x17DeleteUrlsAsyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0e\n" +
	"\fStatsRequest\"O\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"urls_count\x18\x01 \x01(\x05R\turlsCount\x12\x1f\n" +
	"\vusers_count\x18\x02 \x01(\x05R\n" +
	"usersCount2\xf6\x03\n" +
	"\fURLShortener\x12T\n" +
	"\vURLReturner\x12 .urlshortener.URLReturnerRequest\x1a!.urlshortener.URLReturnerResponse\"\x00\x12H\n" +
	"\aShorten\x12\x1c.urlshortener.ShortenRequest\x1a\x1d.urlshortener.ShortenResponse\"\x00\x12_\n" +
	"\fShortenBatch\x12%.urlshortener.ShortenBatchListRequest\x1a&.urlshortener.ShortenBatchListResponse\"\x00\x12?\n" +
	"\x04Urls\x12\x19.urlshortener.UrlsRequest\x1a\x1a.urlshortener.UrlsResponse\"\x00\x12`\n" +
	"\x0fDeleteUrlsAsync\x12$.urlshortener.DeleteUrlsAsyncRequest\x1a%.urlshortener.DeleteUrlsAsyncResponse\"\x00\x12B\n" +
	"\x05Stats\x12\x1a.urlshortener.StatsRequest\x1a\x1b.urlshortener.StatsResponse\"\x00B/Z-github.com/jayjaytrn/URLShortener/proto;protob\x06proto3"

var (
	file_shortener_proto_rawDescOnce sync.Once
	file_shortener_proto_rawDescData []byte
)

func file_shortener_proto_rawDescGZIP() []byte {
	file_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)))
	})
	return file_shortener_proto_rawDescData
}

var file_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_shortener_proto_goTypes = []any{
	(*ShortenRequest)(nil),           // 0: urlshortener.ShortenRequest
	(*ShortenResponse)(nil),          // 1: urlshortener.ShortenResponse
	(*URLReturnerRequest)(nil),       // 2: urlshortener.URLReturnerRequest
	(*URLReturnerResponse)(nil),      // 3: urlshortener.URLReturnerResponse
	(*ShortenBatchListRequest)(nil),  // 4: urlshortener.ShortenBatchListRequest
	(*ShortenBatchRequest)(nil),      // 5: urlshortener.ShortenBatchRequest
	(*ShortenBatchListResponse)(nil), // 6: urlshortener.ShortenBatchListResponse
	(*ShortenBatchResponse)(nil),     // 7: urlshortener.ShortenBatchResponse
	(*UrlsRequest)(nil),              // 8: urlshortener.UrlsRequest
	(*UrlsResponse)(nil),             // 9: urlshortener.UrlsResponse
	(*UserURL)(nil),                  // 10: urlshortener.UserURL
	(*DeleteUrlsAsyncRequest)(nil),   // 11: urlshortener.DeleteUrlsAsyncRequest
	(*DeleteUrlsAsyncResponse)(nil),  // 12: urlshortener.DeleteUrlsAsyncResponse
	(*StatsRequest)(nil),             // 13: urlshortener.StatsRequest
	(*StatsResponse)(nil),            // 14: urlshortener.StatsResponse
}
var file_shortener_proto_depIdxs = []int32{
	5,  // 0: urlshortener.ShortenBatchListRequest.urls:type_name -> urlshortener.ShortenBatchRequest
	7,  // 1: urlshortener.ShortenBatchListResponse.urls:type_name -> urlshortener.ShortenBatchResponse
	10, // 2: urlshortener.UrlsResponse.urls:type_name -> urlshortener.UserURL
	2,  // 3: urlshortener.URLShortener.URLReturner:input_type -> urlshortener.URLReturnerRequest
	0,  // 4: urlshortener.URLShortener.Shorten:input_type -> urlshortener.ShortenRequest
	4,  // 5: urlshortener.URLShortener.ShortenBatch:input_type -> urlshortener.ShortenBatchListRequest
	8,  // 6: urlshortener.URLShortener.Urls:input_type -> urlshortener.UrlsRequest
	11, // 7: urlshortener.URLShortener.DeleteUrlsAsync:input_type -> urlshortener.DeleteUrlsAsyncRequest
	13, // 8: urlshortener.URLShortener.Stats:input_type -> urlshortener.StatsRequest
	3,  // 9: urlshortener.URLShortener.URLReturner:output_type -> urlshortener.URLReturnerResponse
	1,  // 10: urlshortener.URLShortener.Shorten:output_type -> urlshortener.ShortenResponse
	6,  // 11: urlshortener.URLShortener.ShortenBatch:output_type -> urlshortener.ShortenBatchListResponse
	9,  // 12: urlshortener.URLShortener.Urls:output_type -> urlshortener.UrlsResponse
	12, // 13: urlshortener.URLShortener.DeleteUrlsAsync:output_type -> urlshortener.DeleteUrlsAsyncResponse
	14, // 14: urlshortener.URLShortener.Stats:output_type -> urlshortener.StatsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_shortener_proto_init() }
func file_shortener_proto_init() {
	if File_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_proto_msgTypes,
	}.Build()
	File_shortener_proto = out.File
	file_shortener_proto_goTypes = nil
	file_shortener_proto_depIdxs = nil
}
